Vagrant.configure("2") do |config|


  config.vm.provision "shell", path: "flask.sh"

config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "private_network", type: "dhcp"

config.vm.synced_folder  "python", "/home/vagrant/flask-project",type:"virtualbox"




 config.vm.box = "ubuntu/trusty64"
end

